
package lectorpnr.configurar;

import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lectorpnr.MetodosStaticos;
import lectorpnr.datos.db.Conexion;
import lectorpnr.datos.db.Parametros;


public class FrameConfiguracion extends javax.swing.JFrame {

    Parametros param = null;
    public FrameConfiguracion() {
        initComponents();
        param = Parametros.getInstance();
        try { 
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) { 
           
        }
        
        this.setTitle("Lector");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setResizable(false);
        this.setIconImage(new ImageIcon(getClass().getResource("ico_avion.gif")).getImage());
        inicializar();
       
    }
    
    
    private void inicializar(){
        this.txt_ruta_lectura.setText(param.getRuta_lectura());
        this.txt_ruta_leidos.setText(param.getRuta_leidos());
        this.txt_ruta_errores.setText(param.getRuta_error());
        
        
        this.txt_ruta_lectura.setMaximumSize(new Dimension(280,20));
        this.txt_ruta_leidos.setMaximumSize(new Dimension(280,20));
        this.txt_ruta_errores.setMaximumSize(new Dimension(280,20));        
                
        this.txt_servidor.setMaximumSize(new Dimension(335, 20));
        this.txt_usuario.setMaximumSize(new Dimension(335, 20));
        this.txt_contrasena.setMaximumSize(new Dimension(335, 20));        
        this.txt_tiempo.setMaximumSize(new Dimension(335, 20));        
                
        this.txt_servidor.setText(param.getServidor());
        this.txt_usuario.setText(param.getUsuario());
        this.txt_contrasena.setText(param.getContrasena());
        this.txt_tiempo.setText(param.getTiempo_conexion()+"");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConfiguracion = new javax.swing.JLabel();
        bnt_examinar_lectura = new javax.swing.JButton();
        lblRutaLectura = new javax.swing.JLabel();
        txt_ruta_lectura = new javax.swing.JTextField();
        txt_ruta_leidos = new javax.swing.JTextField();
        bnt_examinar_leidos = new javax.swing.JButton();
        lblRutaLeidos = new javax.swing.JLabel();
        txt_ruta_errores = new javax.swing.JTextField();
        bnt_examinar_errores = new javax.swing.JButton();
        lblRutaErrores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblDatosDeLectura = new javax.swing.JLabel();
        lblDatosConexion = new javax.swing.JLabel();
        lblServidor = new javax.swing.JLabel();
        txt_servidor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txt_contrasena = new javax.swing.JPasswordField();
        btn_probar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        lblTiempoConsulta = new javax.swing.JLabel();
        txt_tiempo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setTitle("Configuración");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblConfiguracion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConfiguracion.setText("Configuración");

        bnt_examinar_lectura.setText("Examinar...");
        bnt_examinar_lectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_examinar_lecturaActionPerformed(evt);
            }
        });

        lblRutaLectura.setText("Ruta lectura ");

        bnt_examinar_leidos.setText("Examinar...");
        bnt_examinar_leidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_examinar_leidosActionPerformed(evt);
            }
        });

        lblRutaLeidos.setText("Ruta leidos   ");

        bnt_examinar_errores.setText("Examinar...");
        bnt_examinar_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_examinar_erroresActionPerformed(evt);
            }
        });

        lblRutaErrores.setText("Ruta errores");

        lblDatosDeLectura.setText("Datos de lectura");

        lblDatosConexion.setText("Datos de conexión");

        lblServidor.setText("Servidor");

        txt_servidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_servidorActionPerformed(evt);
            }
        });

        jLabel8.setText("Usuario");

        lblContrasena.setText("Contraseña");

        btn_probar.setText("Probar Conexión");
        btn_probar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_probarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        lblTiempoConsulta.setText("Tiempo consulta");

        txt_tiempo.setText("            ");
        txt_tiempo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tiempoKeyPressed(evt);
            }
        });

        jLabel11.setText("minutos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRutaErrores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_ruta_errores))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRutaLeidos)
                                .addGap(6, 6, 6)
                                .addComponent(txt_ruta_leidos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRutaLectura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addComponent(txt_ruta_lectura, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bnt_examinar_errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnt_examinar_leidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bnt_examinar_lectura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblDatosDeLectura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblConfiguracion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblServidor)
                            .addComponent(jLabel8)
                            .addComponent(lblContrasena))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_usuario)
                            .addComponent(txt_servidor)
                            .addComponent(txt_contrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_probar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblDatosConexion))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTiempoConsulta)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancelar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblConfiguracion)
                .addGap(18, 18, 18)
                .addComponent(lblDatosDeLectura)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_examinar_lectura)
                    .addComponent(lblRutaLectura)
                    .addComponent(txt_ruta_lectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_examinar_leidos)
                    .addComponent(lblRutaLeidos)
                    .addComponent(txt_ruta_leidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_examinar_errores)
                    .addComponent(lblRutaErrores)
                    .addComponent(txt_ruta_errores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDatosConexion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServidor)
                    .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasena)
                    .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoConsulta)
                    .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btn_probar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txt_ruta_errores.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_examinar_lecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_examinar_lecturaActionPerformed
        this.txt_ruta_lectura.setText(MetodosStaticos.abrirArchivo(this));
    }//GEN-LAST:event_bnt_examinar_lecturaActionPerformed

    private void bnt_examinar_leidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_examinar_leidosActionPerformed
       this.txt_ruta_leidos.setText(MetodosStaticos.abrirArchivo(this));
    }//GEN-LAST:event_bnt_examinar_leidosActionPerformed

    private void bnt_examinar_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_examinar_erroresActionPerformed
       this.txt_ruta_errores.setText(MetodosStaticos.abrirArchivo(this));
    }//GEN-LAST:event_bnt_examinar_erroresActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (    this.txt_ruta_lectura.getText().equals("") ||
                this.txt_ruta_leidos.getText().equals("") ||
                this.txt_ruta_errores.getText().equals("") ||
                this.txt_servidor.getText().equals("") ||
                this.txt_usuario.getText().equals("") ||
                this.txt_contrasena.getPassword().equals("") ||
                this.txt_tiempo.getText().equals("") ) {
            
            JOptionPane.showMessageDialog(rootPane,"Debe ingresar todos los campos." );
            return;
        }
        
        String pass = "";
        for (char object : txt_contrasena.getPassword()) {
            pass +=object;
        }
        
        param.setRuta_lectura(this.txt_ruta_lectura.getText());
        param.setRuta_leidos(this.txt_ruta_leidos.getText());
        param.setRuta_error(this.txt_ruta_errores.getText());
        param.setServidor(this.txt_servidor.getText());
        param.setUsuario(this.txt_usuario.getText());
        param.setContrasena(pass);
        param.setTiempo_conexion(Integer.parseInt(this.txt_tiempo.getText()));
        
        
        if (param.guardarCambios()) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_tiempoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tiempoKeyPressed
        txt_tiempo.addKeyListener(new KeyAdapter() {
             @Override
             public void keyTyped(KeyEvent e) {
                 char vChar = e.getKeyChar();
                 if (!(Character.isDigit(vChar)
                         || (vChar == KeyEvent.VK_BACK_SPACE)
                         || (vChar == KeyEvent.VK_DELETE))) {
                     e.consume();
                 }
             }
         });
    }//GEN-LAST:event_txt_tiempoKeyPressed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        inicializar();
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_probarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_probarActionPerformed
        String pass = "";
        for (char object : txt_contrasena.getPassword()) {
            pass +=object;
        }
        boolean resp = Conexion.probarConexion(this.txt_servidor.getText(), this.txt_usuario.getText(), pass);
        if (resp) {
            JOptionPane.showMessageDialog(rootPane,"¡Conexión exitosa!" );
        }else{
            JOptionPane.showMessageDialog(rootPane,"No se ha podido conectar" );
        }
    }//GEN-LAST:event_btn_probarActionPerformed

    private void txt_servidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_servidorActionPerformed
      
    }//GEN-LAST:event_txt_servidorActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_examinar_errores;
    private javax.swing.JButton bnt_examinar_lectura;
    private javax.swing.JButton bnt_examinar_leidos;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_probar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblDatosConexion;
    private javax.swing.JLabel lblDatosDeLectura;
    private javax.swing.JLabel lblRutaErrores;
    private javax.swing.JLabel lblRutaLectura;
    private javax.swing.JLabel lblRutaLeidos;
    private javax.swing.JLabel lblServidor;
    private javax.swing.JLabel lblTiempoConsulta;
    private javax.swing.JPasswordField txt_contrasena;
    private javax.swing.JTextField txt_ruta_errores;
    private javax.swing.JTextField txt_ruta_lectura;
    private javax.swing.JTextField txt_ruta_leidos;
    private javax.swing.JTextField txt_servidor;
    private javax.swing.JTextField txt_tiempo;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
